# Use official Python base image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the contents of the current directory into the container
COPY . .

# Run the Python script
CMD ["python", "app.py"]
