name: Run Python in Docker

on:
  push:
    paths:
      - '**.py'
      - 'Dockerfile'
      - '.github/workflows/docker-run.yml'
  workflow_dispatch:

jobs:
  run-docker-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Docker version
        run: docker -v

      - name: Build Docker image
        run: docker build -t python-docker-hello .

      - name: Run Docker container
        run: docker run python-docker-hello
