name: Docker Run

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hello World
        run: echo "Hello World"

      - name: Show Docker version
        run: docker -v
        
      - name: Build Docker image
        run: docker build -t python-docker-hello .

      - name: Run Docker container
        run: docker run --rm python-docker-hello
